    # ==========================================
    # TAB 3: AI FLASHCARD MAKER
    # ==========================================
    with tab3:
        st.header("⚡ Interactive Flashcard Maker")
        st.write("Turn any topic or text notes into quick-study flashcards generated by AI.")

        # User Input
        study_subject = st.text_input("Enter study topic for flashcards:", placeholder="e.g., Periodic Table, Spanish Verbs, WW2 Timeline", key="card_topic")
        card_count = st.slider("Number of cards:", min_value=3, max_value=10, value=5, key="card_count_slider")

        if st.button("🚀 Build Flashcard Deck"):
            if not study_subject:
                st.warning("Please enter a topic.")
            else:
                with st.spinner("AI is synthesizing your flashcards..."):
                    import json
                    card_prompt = f"""
                    Create a list of exactly {card_count} study flashcards about '{study_subject}'. 
                    Provide the output strictly as a JSON array of objects, where each object has a 'question' and an 'answer' key. 
                    Do not include markdown syntax formatting blocks, output only the raw JSON.
                    Example:
                    [
                        {{"question": "What is the capital of Japan?", "answer": "Tokyo"}}
                    ]
                    """
                    try:
                        response = client.models.generate_content(
                            model='gemini-2.5-flash',
                            contents=card_prompt
                        )
                        # Parse and clean AI string into safe Python list
                        raw_text = response.text.strip().replace("```json", "").replace("```", "")
                        st.session_state['app_deck'] = json.loads(raw_text)
                        st.session_state['app_deck_index'] = 0
                        st.success("Deck created successfully!")
                    except Exception as e:
                        st.error(f"Failed to generate flashcards: {e}")

        # Display the deck interactively if it exists in session memory
        if 'app_deck' in st.session_state and st.session_state['app_deck']:
            current_deck = st.session_state['app_deck']
            current_idx = st.session_state['app_deck_index']
            
            st.write(f"Card {current_idx + 1} of {len(current_deck)}")
            active_card = current_deck[current_idx]
            
            # Display interactive boxes
            with st.container(border=True):
                st.markdown(f"### ❓ **Question:**\n{active_card['question']}")
                with st.expander("👁️ Reveal Answer"):
                    st.markdown(f"### ✨ **Answer:**\n{active_card['answer']}")
            
            # Nav buttons
            c1, c2 = st.columns(2)
            with c1:
                if st.button("⏮️ Back") and current_idx > 0:
                    st.session_state['app_deck_index'] -= 1
                    st.rerun()
            with c2:
                if st.button("Next ⏭️") and current_idx < len(current_deck) - 1:
                    st.session_state['app_deck_index'] += 1
                    st.rerun()
